version: "3.3"
services:
  goserver:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 9501:8081
    environment:
      LISTEN: ":8081"
      PROVIDERS: "api.giphy.com:443,google.com:443"